.TH "frei" "1" 

.SH "NAME"
.PP
frei - modern replacement for the 'free' command-line utility

.SH "SYNOPSIS"
.PP
frei [OPTIONS...]

.SH "OPTIONS"

.SS "-h"
.PP
Display human-readable numbers (implies `-numbers`)

.SS "-help"
.PP
Print help message and exit

.SS "-key"
.PP
Display color key

.SS "-numbers"
.PP
Print numbers in addition to the chart

.SS "-version"
.PP
Display version and exit

.SH "DESCRIPTION"
.PP
frei is a modern replacement for the 'free' command-line utility which gives information about memory usage by drawing a colorful chart instead of displaying just the numbers

.SH "AUTHOR"
.PP
alexcoder04 <alexcoder04@protonmail.com>

